### ISSUE TITLE
Accommodate Tests that run KOEO — Task 8 proposal

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1039]
Tests that run KOEO are problematic for multiple tests.  Here they elicit a presumed false failure when they run and complete before they can be queried. One heuristic is to collect all the KOEO completions at the end of the part 1 test and excuse or warn the part 1 completed results from future erasure failures.

15:30:58.9386 Sending DM7 for DM30 to Engine #1 (0) for SPN 157
15:30:58.9421 18E300F9 [8] F7 9D 00 1F FF FF FF FF (TX)
15:30:58.9526 18A4F900 [48] F7 9D 00 10 82 01 00 FB FF FF FF FF F7 9D 00 12 82 01 00 FB FF FF FF FF F7 9D 00 07 82 01 DF 10 7C 15 00 00 F7 9D 00 07 82 01 DF 10 6C DC C4 09
DM30 from 0: [
  **_SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -40,000, Value: 3,190, Max: 15,000 kPa
  SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -15,000, Value: 3,190, Max: 524,280 kPa_**
  SPN 157 FMI 16 (SLOT 386) Result: Test Not Complete.
  SPN 157 FMI 18 (SLOT 386) Result: Test Not Complete.
]
FAIL: 6.9.8.6.c - Engine #1 (0) did not erase Test Results data

15:58:04.8703 Sending DM7 for DM30 to Engine #1 (0) for SPN 157
15:58:04.8733 18E300F9 [8] F7 9D 00 1F FF FF FF FF (TX)
15:58:04.8828 18A4F900 [48] F7 9D 00 10 82 01 00 FB FF FF FF FF F7 9D 00 12 82 01 00 FB FF FF FF FF F7 9D 00 07 82 01 79 10 7C 15 00 00 F7 9D 00 07 82 01 79 10 6C DC C4 09
DM30 from 0: [
  SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -40,000, Value: 2,170, Max: 15,000 kPa
  SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -15,000, Value: 2,170, Max: 524,280 kPa
  SPN 157 FMI 16 (SLOT 386) Result: Test Not Complete.
  SPN 157 FMI 18 (SLOT 386) Result: Test Not Complete.
]
FAIL: 6.12.9.4.c - Engine #1 (0) did not erase Test Results data
FAIL: 6.12.9.4.c - Engine #1 (0) partially erased diagnostic information

This is also observed for Test 9.10.  Part 1 shows the ran KOEO

Engine #1 (0) Test Results:
SPN 102 FMI 16 (SLOT 388) Result: Test Not Complete.
SPN 102 FMI 18 (SLOT 388) Result: Test Not Complete.
SPN 102 FMI 10 (SLOT 388) Result: Test Not Complete.
SPN 157 FMI 16 (SLOT 386) Result: Test Not Complete.
SPN 157 FMI 18 (SLOT 386) Result: Test Not Complete.
**_SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -40,000, Value: 2,470, Max: 15,000 kPa
SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -15,000, Value: 2,470, Max: 524,280 kPa_**
SPN 651 FMI 7 (SLOT 256) Result: Test Not Complete.
SPN 652 FMI 7 (SLOT 256) Result: Test Not Complete.
SPN 653 FMI 7 (SLOT 256) Result: Test Not Complete.
SPN 654 FMI 7 (SLOT 256) Result: Test Not Complete.
SPN 655 FMI 7 (SLOT 256) Result: Test Not Complete.
SPN 656 FMI 7 (SLOT 256) Result: Test Not Complete.
SPN 1322 FMI 11 (SLOT 12) Result: Test Not Complete.
SPN 1323 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1323 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1324 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1324 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1325 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1325 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1326 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1326 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1327 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1327 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1328 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1328 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 3058 FMI 16 (SLOT 388) Result: Test Not Complete.
SPN 3058 FMI 18 (SLOT 388) Result: Test Not Complete.
SPN 3058 FMI 10 (SLOT 388) Result: Test Not Complete.
SPN 3216 FMI 2 (SLOT 348) Result: Test Not Complete.
SPN 3216 FMI 20 (SLOT 348) Result: Test Not Complete.
SPN 3216 FMI 21 (SLOT 348) Result: Test Not Complete.
SPN 3216 FMI 10 (SLOT 64) Result: Test Not Complete.
SPN 3217 FMI 20 (SLOT 12) Result: Test Not Complete.
SPN 3217 FMI 21 (SLOT 12) Result: Test Not Complete.
SPN 3218 FMI 2 (SLOT 12) Result: Test Not Complete.
SPN 3226 FMI 2 (SLOT 348) Result: Test Not Complete.
SPN 3226 FMI 20 (SLOT 348) Result: Test Not Complete.
SPN 3226 FMI 21 (SLOT 348) Result: Test Not Complete.
SPN 3226 FMI 10 (SLOT 256) Result: Test Not Complete.
SPN 3227 FMI 20 (SLOT 12) Result: Test Not Complete.
SPN 3227 FMI 21 (SLOT 12) Result: Test Not Complete.
SPN 3228 FMI 2 (SLOT 12) Result: Test Not Complete.
SPN 3251 FMI 10 (SLOT 355) Result: Test Not Complete.
SPN 3362 FMI 31 (SLOT 355) Result: Test Not Complete.
SPN 3521 FMI 18 (SLOT 256) Result: Test Not Complete.
SPN 3936 FMI 2 (SLOT 403) Result: Test Not Complete.
SPN 4331 FMI 18 (SLOT 306) Result: Test Not Complete.
SPN 4334 FMI 18 (SLOT 355) Result: Test Not Complete.
SPN 4364 FMI 31 (SLOT 306) Result: Test Not Complete.
SPN 4752 FMI 18 (SLOT 68) Result: Test Not Complete.
SPN 4794 FMI 31 (SLOT 12) Result: Test Not Complete.
SPN 4795 FMI 31 (SLOT 306) Result: Test Not Complete.
SPN 4796 FMI 31 (SLOT 68) Result: Test Not Complete.
SPN 5024 FMI 10 (SLOT 256) Result: Test Not Complete.
SPN 5024 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 5024 FMI 10 (SLOT 333) Result: Test Not Complete.
SPN 5031 FMI 10 (SLOT 64) Result: Test Not Complete.
SPN 5031 FMI 10 (SLOT 256) Result: Test Not Complete.
SPN 5031 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 5285 FMI 18 (SLOT 64) Result: Test Not Complete.
SPN 5298 FMI 18 (SLOT 12) Result: Test Not Complete.
SPN 5298 FMI 17 (SLOT 12) Result: Test Not Complete.
SPN 5319 FMI 31 (SLOT 460) Result: Test Not Complete.
SPN 5397 FMI 31 (SLOT 12) Result: Test Not Complete.
SPN 5835 FMI 21 (SLOT 390) Result: Test Not Complete.
SPN 6773 FMI 7 (SLOT 12) Result: Test Not Complete.
SPN 6773 FMI 16 (SLOT 403) Result: Test Not Complete.
SPN 6777 FMI 10 (SLOT 256) Result: Test Not Complete.
SPN 7329 FMI 2 (SLOT 306) Result: Test Not Complete.
SPN 7329 FMI 2 (SLOT 306) Result: Test Not Complete.

**Comment by ericthomasswenson** [comment]
For Part 1, one potential heuristic is to warn for completed tests and fail if the number of completed tests exceeds a figure of merit.  This figure of merit could be a single digit percentage, or a user Entered (alternate) limit defined by the certificate holder’s certificate application data submission.

**Comment by ericthomasswenson** [comment]
Otherwise CARB must accept that there can never be a J1939-84 test with zero failures.
Collaboration with CARB will be required to create more specific performance requirements.

**Comment by ericthomasswenson** [comment]
Let’s get deletion detection to work with what we have now.

**Comment by ericthomasswenson** [comment]
6.12.1       DM7 / DM30 / DM58: Command Non-Continuously Monitored Test/Scaled Test Results
6.12.1.1      Actions
a.     DS DM7 with TID 247 using FMI 31 for each SP identified as providing test results in a DM24 response in step 6.1.4.1 to the SP’s respective OBD ECU. 
b.     Create list of ECU address+SPN+FMI supported test results.[1]
c.     Record those test results that are received as complete for each OBD ECU.  // proposal for #1139.

[1] Test results are expected only from the OBD ECU that listed the SPN with test results supported in its DM24 response. Global queries (DM7 messages) for test results can oversubscribe TP.BAM resources. As the DM7 message is a command, 00E300h is the expected PGN data in a NACK response for DM30 or DM58 requests using DM7. See SAE J1939-21 Appendix B.

A.5.6.   Test results
a.   DM7/DM30 Test Results shall report all test results with initialized results and limits (all 00h or FB00h for results and FFFFh for limits). Test results recorded as complete in 6.1.12.1.c are excused here, as they are presumed to complete under KOEO conditions, and create a false failure here. // proposal for #1130

**Comment by ericthomasswenson** [comment]
Section A.7 describes the evaluation of test results, including the definition of a minimum set for SPNs and FMIs to be supported as test results, for the HD OBD monitoring requirements given. 
1.	Each ECU/device that indicates one or more SPs are supported for test results with a DM24 response shall be evaluated separately. The request (DM7) and response (DM30) for test results shall:
a.	Fail if no test result (comprised of a SPN+FMI with a test result and a minimum and maximum test limit) for an SP indicated as supported is actually reported from the ECU/device that indicated support.
b.	Fail if any test result does not report the test result/min test limit/max test limit as initialized (after code clear) values (either FB00h/FFFFh/FFFFh or 0000h/0000h/0000h), **_unless reported as completed during KOEO operation in Part 1._**

**Comment by ericthomasswenson** [comment]
See #1130 for DTCs that don’t run.

**Comment by battjt** [comment]
6.1.12.1.c Create list of complete tests
6.8.12.10 omission...
more updates to be made.

**Comment by ericthomasswenson** [comment]
Implement sequentially with #1130

**Comment by ericthomasswenson** [comment]
Omissions for other deletion evaluations were noted in the review which will be corrected in the artifact draft.

**Comment by ericthomasswenson** [comment]
Initialized test results are FB00 FFFF FFFFh or 
(0000 0000 0000h) for older implementations. 

Anything else (not initialized) may be considered complete. 

FFFFh is a valid upper limit … 

Let’s not bother trying to figure out FFFFh as a lower limit (the data could be signed where the left most bit is a sign).

**Comment by ericthomasswenson** [comment]
The list of complete tests collected in 6.1.12.1.c identifies those tests (labeled with a DTC by DM7) that run KOEO and are not expected to be observed as initialized (FB00 FFFF FFFFh) (ever) subsequently in parts 2-12.

**Comment by markmorrisoncummins** [comment]
We are still seeing failures in part 9 for uninitialized tests that were already identified in part 1.

Part 1:

> 13:46:13.2581 Sending DM7 for DM30 to Engine #1 (0) for SPN 157
> 13:46:13.2601 18E300F9 [8] F7 9D 00 1F FF FF FF FF (TX)
> 13:46:13.2701 1CA4F900 [48] F7 9D 00 10 82 01 00 FB FF FF FF FF F7 9D 00 12 82 01 00 FB FF FF FF FF F7 9D 00 07 82 01 26 0F 7C 15 00 00 F7 9D 00 07 82 01 26 0F 6C DC C4 09
> DM30 from Engine #1 (0): [
>   SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -40,000, Value: -1,220, Max: 15,000 kPa
>   SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -15,000, Value: -1,220, Max: 524,280 kPa
>   SPN 157 FMI 16 (SLOT 386) Result: Test Not Complete.
>   SPN 157 FMI 18 (SLOT 386) Result: Test Not Complete.
> ]
> FAIL: 6.1.12.2.a (A.7.1.b) - Test result for SP 157 FMI 7 from Engine #1 (0) does not report the test result/min test limit/max test limit initialized properly
> FAIL: 6.1.12.2.a (A.7.1.b) - Test result for SP 157 FMI 7 from Engine #1 (0) does not report the test result/min test limit/max test limit initialized properly

Part 9:

> 13:59:10.6831 Sending DM7 for DM30 to Engine #1 (0) for SPN 157
> 13:59:10.6821 18E300F9 [8] FA 9D 00 07 FF FF FF FF (TX)
> 13:59:10.6921 1CA4F900 [24] FA 9D 00 07 82 01 1F 0F 7C 15 00 00 FA 9D 00 07 82 01 1F 0F 6C DC C4 09
> DM30 from Engine #1 (0): [
>   SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -40,000, Value: -1,290, Max: 15,000 kPa
>   SPN 157 FMI 7 (SLOT 386) Result: Test Passed. Min: -15,000, Value: -1,290, Max: 524,280 kPa
> ]
> FAIL: 6.9.10.2.a - Engine #1 (0) reported test result for SPN = 157, FMI = 7 is not initialized
> FAIL: 6.9.10.2.a - Engine #1 (0) reported test result for SPN = 157, FMI = 7 is not initialized

This code snip below is from "Part09Step10Controller.java". It looks like it fails when the test results are not initialized in part 1 and also not initialized in part 9. We want to fail when the result is initialized in part 1 and not initialized in part 9.

```java
boolean fromPart1 = moduleInformation.getInitialized_1_12_Tests()
                                     .stream()
                                     .filter(t -> t.getSpn() == spn
                                             && t.getFmi() == fmi)
                                     .findAny()
                                     .isPresent();
if (!fromPart1 && !str.isInitialized()) {
    addFailure("6.9.10.2.a - " + moduleName
            + " reported test result for SPN = " + str.getSpn()
            + ", FMI = " + str.getFmi()
            + " is not initialized");
}
``` 



part 1 | part 9 | expected result | actual result
-- | -- | -- | --
initialized (not complete) | initialized (not complete) | PASS | PASS
initialized (not complete) | not initialized (complete) | FAIL | PASS
not initialized (complete) | initialized (not complete) | PASS | PASS
not initialized (complete) | not initialized (complete) | PASS | FAIL

**Comment by ericthomasswenson** [comment]
Joe ... please use 1307 for the released correction
